# Generated by Django 5.0.6 on 2024-07-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
